{{- if .Values.credentials.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bweso.credentialsSecretName" . }}
  labels:
    {{- include "bweso.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.credentials.existingSecret.keys.clientId }}: {{ .Values.credentials.clientId | quote }}
  {{ .Values.credentials.existingSecret.keys.clientSecret }}: {{ .Values.credentials.clientSecret | quote }}
  {{ .Values.credentials.existingSecret.keys.masterPassword }}: {{ .Values.credentials.masterPassword | quote }}
  {{- if and .Values.auth.enabled (not .Values.auth.scopedPolicy.existingSecret.name) }}
  {{ .Values.credentials.existingSecret.keys.webhookToken }}: {{ .Values.credentials.webhookToken | quote }}
  {{- end }}
{{- end }}
